spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_organizer
    username: root
    password: enter
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  application:
    name: TASK-ORGANIZER

jwt:
  secret: mySecretKey